name: 上游同步

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *" # 每天
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    name: 从上游仓库同步最新提交
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # 第1步：运行标准的检出动作
      - name: 检出目标仓库
        uses: actions/checkout@v4

      # 第2步：运行同步动作
      - name: 同步上游变更
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: tangly1024/NotionNext
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # 自动生成，无需设置

          # 将 test_mode 设置为 true 可运行测试而非真实同步！！
          test_mode: false

      - name: 同步检查
        if: failure()
        run: |
          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次。"
          exit 1
